"""Add index on alert.provider_type for performance

Revision ID: f8a9b2c3d4e5
Revises: 9dd1be4539e0
Create Date: 2025-12-17 15:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8a9b2c3d4e5"
down_revision = "9dd1be4539e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_alert_provider_type",
        "alert",
        ["provider_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_alert_provider_type", table_name="alert")
    # ### end Alembic commands ###
